INSERT INTO CARGO (ID, DESCRICAO) VALUES (NULL, 'GERENTE');
INSERT INTO CARGO (ID, DESCRICAO) VALUES (NULL, 'SUPERVISOR');
INSERT INTO CARGO (ID, DESCRICAO) VALUES (NULL, 'ADMINISTRATIVO');

INSERT INTO PERFIL (ID, DESCRICAO) VALUES (NULL, 'ADMINISTRATIVO');
INSERT INTO PERFIL (ID, DESCRICAO) VALUES (NULL, 'OPERACIONAL');

INSERT INTO USUARIO (ID, NOME, CPF, SEXO, DATA_NASCIMENTO, CARGO_ID, PERFIL_ID, STATUS_REGISTRO) VALUES (NULL, 'JOSE DE ALMENDA CAMPOS', '27112849055', 'MASCULINO', '2018-02-26', 1, 2, 'ATIVO');

INSERT INTO USUARIO (ID, NOME, CPF, SEXO, DATA_NASCIMENTO, CARGO_ID, PERFIL_ID, STATUS_REGISTRO) VALUES (NULL, 'CANDIDO SALES', '46474650044', 'MASCULINO', '2018-12-17', 1, 1, 'ATIVO');

INSERT INTO USUARIO (ID, NOME, CPF, SEXO, DATA_NASCIMENTO, CARGO_ID, PERFIL_ID, STATUS_REGISTRO) VALUES (NULL, 'EDER ALEIXO SALES', '84343651037', 'MASCULINO', '2018-07-04', 2, 2, 'ATIVO');

INSERT INTO USUARIO (ID, NOME, CPF, SEXO, DATA_NASCIMENTO, CARGO_ID, PERFIL_ID, STATUS_REGISTRO) VALUES (NULL, 'ISABELA CAMPOS SANTOS', '78249683080', 'FEMININO', '2008-05-17', 3, 1, 'ATIVO');

INSERT INTO USUARIO (ID, NOME, CPF, SEXO, DATA_NASCIMENTO, CARGO_ID, PERFIL_ID, STATUS_REGISTRO) VALUES (NULL, 'ANDRESSA SALES', '64319925041', 'FEMININO', '2076-12-03', 1, 1, 'ATIVO');

INSERT INTO USUARIO (ID, NOME, CPF, SEXO, DATA_NASCIMENTO, CARGO_ID, PERFIL_ID, STATUS_REGISTRO) VALUES (NULL, 'FERNANDA VENTURINI', '40977865045', 'FEMININO', '2008-05-17', 3, 1, 'ATIVO');
